### ISSUE TITLE
Any interest in joining the trac-hacks organization?

### ISSUE THREAD

**Issue by rjollos** [trac-hacks/tracdocs#6]
Hi,

I'm an administrator for trac-hacks.org.  We've created an organization on GitHub and are inviting authors of trac-hacks plugins to join the organization.  Your repository could be transferred into the organization as described in the [GitHub docs](https://help.github.com/articles/transferring-a-repository/).  You'd retain full control over the repository, but the hope is that it will be easier for users on GitHub to fine trac-hacks plugins, including yours, by viewing the trac-hacks organization.

In the future, if you choose to no longer maintain the plugin, the organization would be able to provide commit access to new developers.  This would only be done with your permission, as has been the policy for plugins hosted on trac-hacks.org.  If you've already decided to no longer maintain the plugin, we would particularly appreciate you transferring the plugin to the trac-hacks organization so that we can help find new maintainers for it.

Finally, creating the trac-hacks organization is a work in progress. I appreciate if you have any suggestions on how to best support the community of trac plugin developers on GitHub. I'll be writing a blog post soon with more information and will follow-up here with a link to that post.

Kind regards,
- Ryan

**Comment by mrjbq7** [comment]
Hi, that sounds interesting, but I'm not sure how "ownership" of organization repositories works.  Would I be assigned by the organization as an "owner" of my repo? Could you take that away for some reason without my agreement?  I'm just not sure how that all works.

**Comment by rjollos** [comment]
You'd be administrator of the repository and in control of who you grant r/w access to. The  3 other admins and I technically have full control to grant and revoke permissions, so in theory we could revoke your permissions without your agreement. I can't think of a valid reason for us taking actions like that, and I hope that the [trac community](https://groups.google.com/forum/#!forum/trac-users) would hold anyone accountable for bad behavior like that. I've spent years working in the trac community and never had a conflict with anyone. It's important for me to retain a good reputation and to forge good relationships with everyone.

I had hoped to come up with a simpler solution that would avoid these "technically yes we can do that" situations, but it does not seem to be possible on GitHub. Repository tags would be the simplest solution, but GitHub doesn't support those. Creating an organization and moving repositories seems to be the only solution.

The motivation for this is based on what [Jenkins CI](https://github.com/jenkinsci) has implemented - an index for browsing plugins. By having an organization it will make it easier to Trac users to locate plugins hosted on GitHub. We'll be linking to the organization from Trac and Trac-Hacks.org. The upside for you is hopefully the possibility of more people using your plugin, and more contributors.

**Comment by rjollos** [comment]
Also, you can take a look at [repository access teams](https://help.github.com/articles/permission-levels-for-an-organization-repository/#repository-access-teams). You'd be the only remember of the _Admin access team_ for your repository, unless you choose to add other users. I and 3 other organization admins are in the _Owner team_.

**Comment by mrjbq7** [comment]
Is this something you guys are still interested in?

Would you be able to provide some help with making sure binaries are available on PyPI properly?

**Comment by rjollos** [comment]
> Is this something you guys are still interested in?

You should receive an invite to join the trac-hacks organization. You'll have general Admin access to the trac-hacks organization which will allow you to execute [these steps](https://help.github.com/articles/transferring-a-repository/#transferring-between-user-accounts) and transfer the repository. After you transfer the repository I'll remove you from the Admin team, create an Admin group for your repository and make you the Admin for your repository.

> Would you be able to provide some help with making sure binaries are available on PyPI properly?

Yeah, I'm happy to help with that. Eventually I hope to have some infrastructure on trac-hacks.org for publishing to PyPI, but for now we can just do that manually.

**Comment by mrjbq7** [comment]
Okay, transferred the repo.  You can now make the changes to make me an Admin for tracdocs, tracsql, and tracstats.

**Comment by rjollos** [comment]
Thanks, permissions should be set correctly now for tracdocs.
